# Generated by Django 3.1.5 on 2022-03-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(db_column='fullname', max_length=100)),
                ('phone', models.CharField(db_column='phone', max_length=20)),
            ],
            options={
                'db_table': 'tbClient',
                'managed': True,
            },
        ),
    ]
