# Generated by Django 3.1.5 on 2022-03-04 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_lastconnection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='lastConnection',
        ),
    ]
