# Generated by Django 3.1.5 on 2022-03-04 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_remove_client_lastconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='lastConnection',
            field=models.DateTimeField(db_column='lastConnection', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
