# Generated by Django 3.1.5 on 2022-03-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_client_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(db_column='password', default=1, max_length=255),
            preserve_default=False,
        ),
    ]
