# Generated by Django 3.1.5 on 2022-03-25 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0007_auto_20220323_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(db_column='designation', max_length=100)),
            ],
            options={
                'db_table': 'tbCanal',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(db_column='message', max_length=255)),
                ('dateMsg', models.DateTimeField(auto_now=True, db_column='dateMsg')),
                ('file', models.CharField(db_column='file', max_length=255, null=True)),
                ('isPrivate', models.BooleanField(db_column='isPrivate')),
                ('refCanal', models.ForeignKey(db_column='refCanal', null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.canal')),
                ('refClient', models.ForeignKey(db_column='refClient', on_delete=django.db.models.deletion.CASCADE, related_name='refClient', to='client.client')),
                ('refDestinateur', models.ForeignKey(db_column='refDestinateur', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refDestinateur', to='client.client')),
            ],
        ),
    ]
