# Generated by Django 3.1.5 on 2022-03-30 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_canal_description'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chat',
            table='tbChat',
        ),
    ]
