# Generated by Django 3.1.5 on 2022-03-30 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_auto_20220307_1336'),
        ('chat', '0003_auto_20220330_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='file',
        ),
        migrations.AddField(
            model_name='chat',
            name='refMedia',
            field=models.ForeignKey(db_column='refMedia', null=True, on_delete=django.db.models.deletion.CASCADE, to='video.media'),
        ),
    ]
