# Generated by Django 3.1.5 on 2022-03-02 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(db_column='designation', max_length=100)),
            ],
            options={
                'db_table': 'tbCategory',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=100)),
                ('auteur', models.CharField(db_column='auteur', max_length=100, null=True)),
                ('poster', models.FileField(db_column='poster', null=True, upload_to='media/poster/video/')),
                ('file', models.FileField(db_column='file', upload_to='media/video')),
                ('dateAjout', models.DateTimeField(auto_now_add=True, db_column='dateAjout')),
                ('refCategory', models.ForeignKey(db_column='refCategory', on_delete=django.db.models.deletion.CASCADE, to='video.category')),
            ],
            options={
                'db_table': 'tbVideo',
                'managed': True,
            },
        ),
    ]
