# Generated by Django 3.1.5 on 2022-03-03 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='media',
            table='tbMedia',
        ),
    ]
