# Generated by Django 3.1.5 on 2022-03-04 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_lastconnection'),
        ('video', '0004_auto_20220304_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='refClient',
            field=models.ForeignKey(db_column='refClient', default=1, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
            preserve_default=False,
        ),
    ]
